<div class="form-login-block">
    <?php 
        $this->headTitle(_('Login'));
    ?>
    <div class="header-title ipadpages">
        <div class="h-bg">	
            <h1><?php echo _('Reset password') ?></h1>
        </div>
    </div>
        <?php if ($success) { ?> 
        <div class="content-border login">
            <?php echo _('Please check your email for instructions to activate new password');
            ?>
        </div>
        <?php return true;
        } ?>
    <div class="content-border login container">
        <div class="login-form">
            <?php
            if (isset($err) && !empty($err)){
                echo '<div class="error top_error">'.$err.'</div>';
            }
            echo $this->wrappedForm($form);
            ?>
        </div>
    </div>
</div>