
<div class="form-login-block">
    <?php 
        $this->headTitle(_('Login'));
        //add specific css and js for this page as separate files
        $this->headScript()->appendFile($this->basePath() . '/js/pages/login.js', 'text/javascript');
        $this->headLink()->appendStylesheet($this->basePath() . '/css/pages/login.css');
    ?>
    <div class="header-title ipadpages">
        <div class="h-bg">	
            <h1><?php echo _('Authorization page') ?></h1>
        </div>
    </div>

    <div class="content-border login">
        <div class="login-form">
        <?php
        if (isset($err) && !empty($err)){
            echo '<div class="error top_error">'.$err.'</div>';
        }
        echo $this->wrappedForm($form);
        ?>
        <a href="<?php echo URL.'user/forgotpassword';?>"><?php echo _('Forgot password?');?></a>
        </div>
    </div>
</div>
