<div class="jumbotron">
    <h1><?php echo _('Welcome to New Carcass!'); ?></h1>
</div>
    <?php if ($category) : 
    $title = $category->title;
    $this->headTitle($title);
    ?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<hr>
<?php endif; ?>
<div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9">
        <div class="row">
            <?php foreach ($this->paginator as $product) : ?>
                <div class="col-lg-3">
                    <div class="thumbnail panel panel-default">
                        <img class="img-thumbnail center-block" src="<?php echo $this->resizeImage($product->resource, 300, 300); ?>" />
                        <div class="caption">
                            <a href="<?php echo $this->url('product', array('controller' => 'product', 'action' => 'index', 'slug' => $product->slug)); ?>"><h4><?php echo $this->escapeHtml($product->title); ?></h4></a>
                            <p><span>Type: <a href="<?php echo $this->url('home', array('action' => 'catalog', 'category' => $product->categoryId)); ?>"><?php echo $product->categoryName; ?></a></span></p>
                            <p><span>Price: <?php echo $product->price; ?><?php echo $this->escapeHtml($product->currency); ?></span></p>
                            <a class="btn btn-default center-block" href="<?php echo $this->url('product', array('controller' => 'product', 'action' => 'index', 'slug' => $product->slug)); ?>"><?php echo _('Buy Now') ?> &raquo;</a>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="row">
            <?php
            $route = array(
                        'route' => 'home',
                    );
            if ($categoryId) {
                 $route['category'] = $categoryId;
            }
            echo $this->paginationControl(
                    $this->paginator,
                    'sliding',
                    array('partial/paginator.phtml', 'Catalog'),
                    $route
            );
            ?>
        </div>
    </div>
    <?php echo $this->partial('partial/sidebar.phtml'); ?>
</div>