<?php

namespace Model\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    
    /**
     * 
     * @param type $id
     * @return \Model\Entity\Product
     */
    public function getProductById($id)
    {
        return $this->createQueryBuilder('o')
            ->join('o.type', 't')
            ->select('o, t')
            ->andWhere('o.id = '. $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
