<?php

namespace Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTypeRepository extends EntityRepository {

    public function getCat($id) {

        return $this->createQueryBuilder('type')
                        ->addSelect('product')
                        ->join('type.products', 'product')
                        ->andWhere('type.id = ' . $id)
                        ->getQuery()
                        ->getOneOrNullResult(2);
    }

}
