<?php

namespace Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductAttachmentRepository extends EntityRepository
{
}
