<?php
$this->myviewalias()->prepareControllerAction();
$controller = $this->controller;
$role = $this->getUser()->getRole();
?>
<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name = "format-detection" content = "telephone=no">
        <?php echo $this->headTitle(SITE_NAME)->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basepath('css/jquery.fancybox.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile(URL . 'js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/admin/jquery.fancybox.js')
                ->prependFile($this->basePath() . '/js/jquery-1.9.0.min.js')
        ;
        ?>

    </head>
    <body>
        <div id="wrap">
            <div class="container">
                <div class="navbar header navbar-default navbar-fixed-top" role="navigation">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="<?php echo URL; ?>"><img src=""/></a>
                        </div>
                        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
                            <ul class="nav navbar-nav">
                                <li class="<?= in_array($controller, array('Index')) ? "active " : '' ?>"><a href="<?php echo URL; ?>"><?php echo _('Home') ?></a></li>
                                <?php $countShoppingCartProduct = $this->getShoppingCartHelper()->getCountShoppingCartProduct(); ?>
                                <li class="<?= in_array($controller, array('ShoppingCart')) ? "active " : '' ?>"><a href="<?php echo $this->url('shopping-cart') ?>"><?php echo _('Shopping Cart') ?> <?php if ($countShoppingCartProduct) :?><span class="badge"><?php echo $countShoppingCartProduct; ?></span><?php endif; ?></a></li>
                                <? if ($this->getUser()->isAllowed('Admin\Controller\Product', 'index')) {?>
                                <li><a href="<?php echo $this->basepath('admin/') ?>" class=""><span><?echo _('Admin panel');?></span></a></li>
                                <?}?>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <?php if ($this->getUser()->getUser()->getId()) { ?>
                                    <li><a href="<?php echo URL . 'user/logout'; ?>" class=""><span><?echo _('Logout');?></span></a></li>
                                    <? } else { ?>
                                    <li class="<?= in_array($controller, array('User')) ? "active " : '' ?>"><a href="<?php echo URL . 'user/login'; ?>"><span><?echo _('Login');?></span></a></li>
                                <?php } ?>
                            </ul>
                        </nav><!--/.nav-collapse -->
                    </div>
                </div>            
                <?php echo $this->content; ?>
            </div>
        </div>
        <div class="footer">
            <div class="container">
                <p class="text-muted"><?php printf(_('&copy; %d by Veselov. All rights reserved.'), date('Y')) ?></p>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
