<?php if ($this->pageCount): ?>
    <div class="pager">
        <ul>
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('page' => $this->previous, 'category' => $this->category)); ?>">
                        &laquo;
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        &laquo;
                    </a>
                </li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route, array('page' => $page, 'category' => $this->category)); ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('page' => $this->next, 'category' => $this->category)); ?>">
                        &raquo;
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        &raquo;
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>
